# Generated by Django 3.1 on 2020-10-18 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_register_time_rem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Getassured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userinput1', models.CharField(blank=True, max_length=255)),
                ('usersinput2', models.CharField(blank=True, max_length=255)),
                ('tempscore', models.IntegerField(default=0)),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.response')),
            ],
        ),
    ]
