# Generated by Django 3.1 on 2020-10-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_getassured'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='current_qno',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='getassured',
            name='userinput1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='getassured',
            name='usersinput2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
