# Generated by Django 3.1 on 2020-10-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_register_counter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='getassured',
            old_name='usersinput2',
            new_name='userinput2',
        ),
        migrations.AddField(
            model_name='response',
            name='userinput1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='response',
            name='userinput2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
