# Generated by Django 3.1 on 2020-10-18 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_auto_20201018_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='counter',
        ),
        migrations.RemoveField(
            model_name='response',
            name='current_qno',
        ),
        migrations.RemoveField(
            model_name='response',
            name='userinput1',
        ),
        migrations.RemoveField(
            model_name='response',
            name='userinput2',
        ),
        migrations.DeleteModel(
            name='Getassured',
        ),
    ]
