# Generated by Django 3.1 on 2020-10-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_response_getassured_attemptno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='getassured_attemptno',
        ),
        migrations.AddField(
            model_name='register',
            name='getassured_attemptno',
            field=models.IntegerField(default=1),
        ),
    ]
