# Generated by Django 3.1 on 2020-10-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_auto_20201019_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='getassured_attemptno',
            field=models.IntegerField(default=0),
        ),
    ]
