# Generated by Django 3.1 on 2020-10-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_auto_20201019_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='total_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='response',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
    ]
